[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green = "#bb77ff"
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

# Bright colors
[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'

[colors.primary]
background = "#0b0b0c"
#foreground = "#a7b4da"

[window]
dimensions = { columns = 160, lines = 40 }
title = ""


[font]
size = 13.5

[font.normal]
#family = "Literation Mono Nerd Font"
family = "InconsolataGo Nerd Font Mono"
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "Never" }
